name: AWS Rollback
on:
  workflow_dispatch:
    inputs:
      worker_go_ref:
        description: 'Revision Number, Defaule latest-1'
        required: true
        default: 'latest-1'
env:
  AWS_REGION: "eu-west-3"
  ECR_REPOSITORY: "nodejs-1"
  ECS_SERVICE: "nodejs-service"
  ECS_CLUSTER: "ramazan-test-1"
  ECS_TASK_DEFINITION: ".aws/task-definition.staging.paris.json"
  CONTAINER_NAME: "nodejs-test"
  

jobs:
  Set-variables:
    name: "Rollback"
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set Current Task Revision
        id: current-revision
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.date.outputs.date }}-${{ steps.vars.outputs.sha_short }}
        run: |
          echo "REVISION_NUMBER=$(aws ecs describe-services --cluster ${{ env.ECS_CLUSTER }} --query "services[].taskDefinition" --services ${{ env.ECS_SERVICE }} --output text | cut -d: -f7)" >> $GITHUB_ENV
          echo "REVISION_NAME=$(aws ecs describe-services --cluster ${{ env.ECS_CLUSTER }} --query "services[].taskDefinition" --services ${{ env.ECS_SERVICE }} --output text | cut -d: -f1-6)" >> $GITHUB_ENV
      
      # If revision number picked manually.
      - name: Rollback to previous version
        if: ${{ github.event.inputs.worker_go_ref != 'latest-1' }}
        id: rollback
        run: |
          echo "From github action: ${{ env.NEW_PREVIOUS_REVISION_NUMBER }}"
          echo 'rickrolled'
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --task-definition ${{ env.REVISION_NAME }}:${{ github.event.inputs.worker_go_ref }}

      # If revision number is latest-1  Run below   
      - name: Set Previous Task Revision Number
        id: previous-revision-number
        if: ${{ github.event.inputs.worker_go_ref  == 'latest-1' }}
        run: |
          echo "PREVIOUS_REVISION_NUMBER"=$((${{ env.REVISION_NUMBER }}-1)) >> $GITHUB_ENV

      - name: Checkout The Repo
        uses: actions/checkout@v2
        if: ${{ github.event.inputs.worker_go_ref == 'latest-1' }}

      - name: Check Variables with script
        id: check-variables
        if: ${{ github.event.inputs.worker_go_ref == 'latest-1' }}
        env:
          PREVIOUS_REVISION_NUMBER: ${{ env.PREVIOUS_REVISION_NUMBER }}
        run: |
            chmod +x ./.github/workflows/check-variables.sh
            ./.github/workflows/check-variables.sh ${{ env.ECR_REPOSITORY }} $PREVIOUS_REVISION_NUMBER
        shell: bash

      # NEW_PREVIOUS_REVISION_NUMBER variables comes from check-variables.sh script file.
      - name: Rollback to previous version
        id: rollback
        if: ${{ github.event.inputs.worker_go_ref == 'latest-1' }}
        run: |
          echo "From github action: ${{ env.NEW_PREVIOUS_REVISION_NUMBER }}"
          echo 'rickrolled'
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --task-definition ${{ env.REVISION_NAME }}:${{ env.NEW_PREVIOUS_REVISION_NUMBER }}

